substitutions:
  name: "media-player"
  friendly_name: "Media Player"
  media_player: ""

esphome:
  name_add_mac_suffix: true

packages:
  music_dashboard: !include ../devices/elecrow-crowpanel-esp32-s3-21-rotary/packages.yaml

wifi:
  ap:

captive_portal:
