substitutions:
  firmware_version: "0.0.0"

packages:
  core: !include elecrow-crowpanel-esp32-s3-21-rotary.yaml

esphome:
  project:
    name: jtenniswood.media-player
    version: "${firmware_version}"

dashboard_import:
  package_import_url: github://gurul/music-knob/devices/elecrow-crowpanel-esp32-s3-21-rotary/esphome.yaml@main

improv_serial:
